name: Build and Release Debian Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build .deb package
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [amd64, arm64]
        suite: [bookworm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up QEMU for cross-compilation
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3

      - name: Create Debian container
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --name build-container --platform linux/${{ matrix.platform }} -d -e SUITE=${{ matrix.suite }} -v $PWD/package.sh:/package.sh -v $PWD/distrib:/distrib -w / debian:${{ matrix.suite }}-slim sleep infinity

      - name: Run build script
        run: |
          docker exec build-container bash -c "/package.sh"

      - name: Retrieve built .deb package
        run: |
          PACKAGE_NAME="adguardhome_${{ env.VERSION }}~${{ matrix.suite }}_${{ matrix.platform }}.deb"
          docker cp build-container:/build/$PACKAGE_NAME ./

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package-${{ matrix.platform }}
          path: ./*.deb

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.deb
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
